markdown: kramdown
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "JickYang Tech"

author: "JickYang"
atom-baseurl: "http://jickyang.com"
disqus: "gopherwood"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
